
CREATE TABLE OCUPACION (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(100)
);

CREATE TABLE ESTADO_CIVIL (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(50)
);

CREATE TABLE SEXO (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(25)
);

CREATE TABLE PERSONA (
    CUI INTEGER PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(72),
    SEGUNDO_NOMBRE VARCHAR(73),
    TERCER_NOMBRE VARCHAR(72),
    PRIMER_APELLIDO VARCHAR(72),
    SEGUNDO_APELLIDO VARCHAR(72),
    NIT INTEGER,
    OCUPACION INTEGER,
    ESTADO_CIVIL INTEGER,
    SEXO INTEGER,
    CORREO VARCHAR(250),
    FECHA_NACIMIENTO DATE,
    UBICACION_NACIMIENTO INTEGER,
    RESIDENCIA INTEGER,
    TELEFONO INTEGER,
    FOREIGN KEY (OCUPACION) REFERENCES OCUPACION(ID),
    FOREIGN KEY (ESTADO_CIVIL) REFERENCES ESTADO_CIVIL(ID),
    FOREIGN KEY (SEXO) REFERENCES SEXO(ID)
);

CREATE TABLE DPI (
    NUMERO_SERIE INTEGER PRIMARY KEY,
    CUI INTEGER,
    FECHA_EMISION DATE,
    FECHA_EXPIRACION DATE,
    FOREIGN KEY (CUI) REFERENCES PERSONA(CUI)
);

CREATE TABLE DEPARTAMENTO (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100)
);

CREATE TABLE MUNICIPIO (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DEPARTAMENTO_ID INTEGER,
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE TIPO_ZONA (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(120)
);


CREATE TABLE JURISDICCION (
    ID INTEGER PRIMARY KEY,
    ID_TIPO_ZONA INTEGER,
    NOMBRE VARCHAR(72),
    ID_MUNICIPIO INTEGER,
    FOREIGN KEY (ID_TIPO_ZONA) REFERENCES TIPO_ZONA(ID),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO(ID)
);

CREATE TABLE TIPO_LIBRO (
    ID INTEGER PRIMARY KEY,
    SERIE INTEGER,
    SIMBOLO VARCHAR(1),
    DEPARTAMENTO INTEGER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE NATURALEZA (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(72)
);

CREATE TABLE TIPO_FINCA (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(25)
);

CREATE TABLE TIPO_EDIFICACION (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(45)
);

CREATE TABLE FINCA (
    ID INTEGER PRIMARY KEY,
    FOLIO INTEGER,
    TIPO_LIBRO INTEGER,
    JURISDICCION INTEGER,
    AREA DECIMAL(10,2),
    TIPO_NATURALEZA INTEGER,
    NOMBRE VARCHAR(72),
    TIPO_FINCA INTEGER,
    EDICACION BOOLEAN,
    TIPO_EDIFICACION INTEGER,
    FOREIGN KEY (TIPO_LIBRO) REFERENCES TIPO_LIBRO(ID),
    FOREIGN KEY (JURISDICCION) REFERENCES JURISDICCION(ID),
    FOREIGN KEY (TIPO_NATURALEZA) REFERENCES NATURALEZA(ID),
    FOREIGN KEY (TIPO_FINCA) REFERENCES TIPO_FINCA(ID),
    FOREIGN KEY (TIPO_EDIFICACION) REFERENCES TIPO_EDIFICACION(ID)
);

CREATE TABLE DERECHO_PROPIEDAD (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(250),
    DESCRIPCION BLOB SUB_TYPE TEXT
);

CREATE TABLE MONEDA (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(72),
    SIMBOLO CHAR(1)
);
CREATE TABLE ESTADO_COLEGIADO (
    ID INTEGER PRIMARY KEY,
    ESTADO VARCHAR(35)
);

CREATE TABLE CATEGORIA_COLEGIADO (
    ID INTEGER PRIMARY KEY,
    CATEGORIA VARCHAR(35)
);

CREATE TABLE ESPECIALIDAD_COLEGIADO (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(35)
);

CREATE TABLE COLEGIADO (
    ID INTEGER PRIMARY KEY,
    ID_PERSONA INTEGER,
    DPI INTEGER,
    ESTADO_COLEGIADO INTEGER,
    CATEGORIA INTEGER,
    ESPECIALIDAD INTEGER,
    FECHA_EXPIRACION DATE,
    FECHA_EMISION DATE,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(CUI),
    FOREIGN KEY (DPI) REFERENCES DPI(NUMERO_SERIE),
    FOREIGN KEY (ESTADO_COLEGIADO) REFERENCES ESTADO_COLEGIADO(ID),
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA_COLEGIADO(ID),
    FOREIGN KEY (ESPECIALIDAD) REFERENCES ESPECIALIDAD_COLEGIADO(ID)
);


CREATE TABLE COMPRA_VENTA (
    ID INTEGER PRIMARY KEY,
    MONEDA INTEGER,
    VALOR_INMUEBLE DECIMAL(10,2),
    ID_FINCA INTEGER,
    OBSERVACIONES BLOB SUB_TYPE TEXT,
    COLEGIADO INTEGER,
    FOREIGN KEY (MONEDA) REFERENCES MONEDA(ID),
    FOREIGN KEY (ID_FINCA) REFERENCES FINCA(ID),
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID)
);

CREATE TABLE DESMEMBRACIONES (
    ID INTEGER PRIMARY KEY,
    COLEGIADO INTEGER,
    REPRESENTANTE INTEGER,
    ID_FINCA_MATRIZ INTEGER,
    ID_FINCA_NUEVA INTEGER,
    FECHA_DESMEMBRACION DATE,
    OBSERVACIONES BLOB SUB_TYPE TEXT,
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (ID_FINCA_MATRIZ) REFERENCES FINCA(ID),
    FOREIGN KEY (ID_FINCA_NUEVA) REFERENCES FINCA(ID)
);


CREATE TABLE UNIFICACION (
    ID INTEGER PRIMARY KEY,
    COLEGIADO INTEGER,
    REPRESENTANTE INTEGER,
    ID_FINCA_NUEVA INTEGER,
    AREA DECIMAL(10,2),
    FECHA DATE,
    OBSERVACIONES BLOB SUB_TYPE TEXT,
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (ID_FINCA_NUEVA) REFERENCES FINCA(ID)
);

CREATE TABLE UNIFICACION_FINCAS (
    ID_UNIFICACION INTEGER,
    ID_FINCAS INTEGER,
    FOREIGN KEY (ID_UNIFICACION) REFERENCES UNIFICACION(ID),
    FOREIGN KEY (ID_FINCAS) REFERENCES FINCA(ID)
);

CREATE TABLE TIPO_GRAVAMENES_LICITACIONES (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(72)
);

CREATE TABLE GRAVAMENES_LICITACIONES (
    ID INTEGER PRIMARY KEY,
    ID_UNIFICACION INTEGER,
    TIPO_GRAVAMENES_LICITACIONES INTEGER,
    ID_FINCA INTEGER,
    FOREIGN KEY (ID_UNIFICACION) REFERENCES UNIFICACION(ID),
    FOREIGN KEY (TIPO_GRAVAMENES_LICITACIONES) REFERENCES TIPO_GRAVAMENES_LICITACIONES(ID),
    FOREIGN KEY (ID_FINCA) REFERENCES FINCA(ID)
);


CREATE TABLE TITULACION_SUPLETORIA (
    ID INTEGER PRIMARY KEY,
    JUEZ_COMPOTENTE INTEGER,
    COLEGIADO INTEGER,
    ID_FINCA INTEGER,
    FECHA DATE,
    FOREIGN KEY (JUEZ_COMPOTENTE) REFERENCES PERSONA(CUI),
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (ID_FINCA) REFERENCES FINCA(ID)
);

CREATE TABLE PROPIETARIOS (
    ID INTEGER PRIMARY KEY,
    PERSONA INTEGER,
    TITULACION_SUPLETORIA INTEGER,
    FOREIGN KEY (PERSONA) REFERENCES PERSONA(CUI),
    FOREIGN KEY (TITULACION_SUPLETORIA) REFERENCES TITULACION_SUPLETORIA(ID)
);

CREATE TABLE PUNTO_CARDINALIDAD (
    ID INTEGER PRIMARY KEY,
    DESCRIPCION VARCHAR(25)
);

CREATE TABLE COLIDANTE (
    ID INTEGER PRIMARY KEY,
    ID_INMUEBLE INTEGER,
    PUNTO_CARDINAL INTEGER,
    FOREIGN KEY (ID_INMUEBLE) REFERENCES FINCA(ID),
    FOREIGN KEY (PUNTO_CARDINAL) REFERENCES PUNTO_CARDINALIDAD(ID)
);

CREATE TABLE COORDENADAS (
    ID INTEGER PRIMARY KEY,
    ID_INMUEBLE INTEGER,
    LONGITUD DECIMAL(10,2),
    LATITUD DECIMAL(10,2),
    FOREIGN KEY (ID_INMUEBLE) REFERENCES FINCA(ID)
);

CREATE TABLE TESTIGO (
    ID INTEGER PRIMARY KEY,
    TITULACION_SUPLETORIA INTEGER,
    ID_COLINDANTE INTEGER,
    FOREIGN KEY (TITULACION_SUPLETORIA) REFERENCES TITULACION_SUPLETORIA(ID),
    FOREIGN KEY (ID_COLINDANTE) REFERENCES COLIDANTE(ID)
);

CREATE TABLE ORDEN_DEFUNCION (
    ID INTEGER PRIMARY KEY,
    ID_PERSONA INTEGER,
    CAUSA BLOB SUB_TYPE TEXT,
    UBICACION_FALLECIMIENTO INTEGER,
    FECHA_HORA TIMESTAMP,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(CUI),
    FOREIGN KEY (UBICACION_FALLECIMIENTO) REFERENCES MUNICIPIO(ID)
);

CREATE TABLE TESTAMENTO_HEREDITARIO (
    ID INTEGER PRIMARY KEY,
    ORDEN_DEFUNCION INTEGER,
    COLEGIADO INTEGER,
    REPRESENTANTE_LEGAL INTEGER,
    FECHA_INGRESO DATE,
    FOREIGN KEY (ORDEN_DEFUNCION) REFERENCES ORDEN_DEFUNCION(ID),
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PERSONA(CUI)
);

CREATE TABLE HEREDEROS (
    ID INTEGER PRIMARY KEY,
    ID_PERSONA INTEGER,
    ID_TESTAMENTO_HEREDITARIO INTEGER,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(CUI),
    FOREIGN KEY (ID_TESTAMENTO_HEREDITARIO) REFERENCES TESTAMENTO_HEREDITARIO(ID)
);

CREATE TABLE HEREDITARIO_INTESTADO (
    ID INTEGER PRIMARY KEY,
    ORDEN_DEFUNCION INTEGER,
    COLEGIADO INTEGER,
    REPRESENTANTE_LEGAL INTEGER,
    FECHA_INGRESO DATE,
    FOREIGN KEY (ORDEN_DEFUNCION) REFERENCES ORDEN_DEFUNCION(ID),
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PERSONA(CUI)
);

CREATE TABLE ANOTACIONES (
    ID INTEGER PRIMARY KEY,
    FINCA_ID INTEGER,
    DESCRIPCION BLOB SUB_TYPE TEXT,
    FECHA DATE,
    FOREIGN KEY (FINCA_ID) REFERENCES FINCA(ID)
);

CREATE TABLE BANCO (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(72),
    CODIGO INTEGER,
    DIRECCION VARCHAR(78),
    TELEFONO INTEGER,
    CORREO VARCHAR(70)
);

CREATE TABLE PERIODO (
    ID INTEGER PRIMARY KEY,
    PERIODO VARCHAR(60)
);

CREATE TABLE CREDITO (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(45)
);

CREATE TABLE HIPOTECAS (
    ID INTEGER PRIMARY KEY,
    REPRESENTANTE_LEGAL INTEGER,
    TIPO_CREDITO INTEGER,
    PORCENTAJE INTEGER,
    BANCO INTEGER,
    FECHA_EMISION DATE,
    FECHA_EXPIRACION DATE,
    ID_FINCA INTEGER,
    COLEGIADO INTEGER,
    PERIODO INTEGER,
    FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PERSONA(CUI),
    FOREIGN KEY (TIPO_CREDITO) REFERENCES CREDITO(ID),
    FOREIGN KEY (BANCO) REFERENCES BANCO(ID),
    FOREIGN KEY (ID_FINCA) REFERENCES FINCA(ID),
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (PERIODO) REFERENCES PERIODO(ID)
);

CREATE TABLE PROPIEDAD_HORIZONTAL (
    ID INTEGER PRIMARY KEY,
    FINCA_ID INTEGER,
    DESCRIPCION BLOB SUB_TYPE TEXT,
    FECHA DATE,
    FOREIGN KEY (FINCA_ID) REFERENCES FINCA(ID)
);

CREATE TABLE AMENIDADES (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(100)
);

CREATE TABLE DONACIONES (
    ID INTEGER PRIMARY KEY,
    COLEGIADO INTEGER,
    REPRESENTANTE_LEGAL INTEGER,
    MENSAJE_ACEPTACION BLOB SUB_TYPE TEXT,
    ID_FINCA_DONADA INTEGER,
    FECHA_DONACION DATE,
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PERSONA(CUI),
    FOREIGN KEY (ID_FINCA_DONADA) REFERENCES FINCA(ID)
);

CREATE TABLE PERMUTAS (
    ID INTEGER PRIMARY KEY,
    COLEGIADO INTEGER,
    REPRESENTANTE_LEGAL INTEGER,
    FINCA_ID INTEGER,
    FECHA DATE,
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PERSONA(CUI),
    FOREIGN KEY (FINCA_ID) REFERENCES FINCA(ID)
);

CREATE TABLE ADJUDICACION (
    ID INTEGER PRIMARY KEY,
    COLEGIADO INTEGER,
    REPRESENTANTE_LEGAL INTEGER,
    FINCA_ID INTEGER,
    FECHA DATE,
    FOREIGN KEY (COLEGIADO) REFERENCES COLEGIADO(ID),
    FOREIGN KEY (REPRESENTANTE_LEGAL) REFERENCES PERSONA(CUI),
    FOREIGN KEY (FINCA_ID) REFERENCES FINCA(ID)
);

CREATE TABLE SOCIOS (
    ID INTEGER PRIMARY KEY,
    ID_ADJUDICACION INTEGER,
    SOCIO INTEGER,
    PORCENTAJE INTEGER,
    FOREIGN KEY (ID_ADJUDICACION) REFERENCES ADJUDICACION(ID),
    FOREIGN KEY (SOCIO) REFERENCES PERSONA(CUI)
);

CREATE TABLE DESMEMBRACION (
    ID INTEGER PRIMARY KEY,
    COLEGIADO INTEGER,
    REPRESENTANTE_LEGAL INTEGER,
    FINCA_ID_DESMEMBRAR INTEGER,
    FINCA_ID_NUEVA INTEGER,
    FECHA DATE
);

CREATE TABLE DUPLICADO (
    ID INTEGER PRIMARY KEY,
    FINCA_ID INTEGER
);

CREATE TABLE TIPOS_SERVIDUMBRE (
    ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(200)
);

CREATE TABLE SERVIDUMBRES (
    ID INTEGER PRIMARY KEY,
    TIPO_SERVIDUMBRE INTEGER,
    FINCA_ID INTEGER
);

