


SET TERM ^ ;

CREATE OR ALTER TRIGGER TRIG_OCUPACION_ID FOR OCUPACION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_OCUPACION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_ESTADO_CIVI_ID FOR ESTADO_CIVIL
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ESTADO_CIVI_ID;
END^

CREATE OR ALTER TRIGGER TRIG_SEXO_ID FOR SEXO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_SEXO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_PERSONA_ID FOR PERSONA
BEFORE INSERT
AS
BEGIN
  IF (NEW.CUI IS NULL) THEN
    NEW.CUI = NEXT VALUE FOR GEN_PERSONA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DPI_ID FOR DPI
BEFORE INSERT
AS
BEGIN
  IF (NEW.NUMERO_SERIE IS NULL) THEN
    NEW.NUMERO_SERIE = NEXT VALUE FOR GEN_DPI_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DEPARTAMENTO_ID FOR DEPARTAMENTO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_DEPARTAMENTO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_MUNICIPIO_ID FOR MUNICIPIO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_MUNICIPIO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TIPO_ZONA_ID FOR TIPO_ZONA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TIPO_ZONA_ID;
END^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER TRIGGER TRIG_JURISDICCION_ID FOR JURISDICCION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_JURISDICCION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TIPO_LIBRO_ID FOR TIPO_LIBRO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TIPO_LIBRO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_NATURALEZA_ID FOR NATURALEZA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_NATURALEZA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TIPO_FINCA_ID FOR TIPO_FINCA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TIPO_FINCA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TIPO_EDIFICACION_ID FOR TIPO_EDIFICACION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TIPO_EDIFICACION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_FINCA_ID FOR FINCA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_FINCA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DERECHO_PROPIEDAD_ID FOR DERECHO_PROPIEDAD
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_DERECHO_PROPIEDAD_ID;
END^

CREATE OR ALTER TRIGGER TRIG_MONEDA_ID FOR MONEDA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_MONEDA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_COMPRA_VENTA_ID FOR COMPRA_VENTA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_COMPRA_VENTA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DESMEMBRACIONES_ID FOR DESMEMBRACIONES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_DESMEMBRACIONES_ID;
END^

CREATE OR ALTER TRIGGER TRIG_ESTADO_COLEGIADO_ID FOR ESTADO_COLEGIADO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ESTADO_COLEGIADO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_CATEGORIA_COLEGIADO_ID FOR CATEGORIA_COLEGIADO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_CATEGORIA_COLEGIADO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_ESPECIALIDAD_COLEGIADO_ID FOR ESPECIALIDAD_COLEGIADO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ESPECIALIDAD_COLEGIADO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_COLEGIADO_ID FOR COLEGIADO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_COLEGIADO_ID;
END^

SET TERM ; ^



SET TERM ^ ;

CREATE OR ALTER TRIGGER TRIG_TIPO_GRAVAMENES_LICITACIONES_ID FOR TIPO_GRAVAMENES_LICITACIONES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TIPO_GRAVAMENES_LICITACIONES_ID;
END^

CREATE OR ALTER TRIGGER TRIG_GRAVAMENES_LICITACIONES_ID FOR GRAVAMENES_LICITACIONES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_GRAVAMENES_LICITACIONES_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TITULACION_SUPLETORIA_ID FOR TITULACION_SUPLETORIA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TITULACION_SUPLETORIA_ID;
END^

CREATE OR ALTER TRIGGER TRIG_PROPIETARIOS_ID FOR PROPIETARIOS
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PROPIETARIOS_ID;
END^

CREATE OR ALTER TRIGGER TRIG_PUNTO_CARDINALIDAD_ID FOR PUNTO_CARDINALIDAD
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PUNTO_CARDINALIDAD_ID;
END^

CREATE OR ALTER TRIGGER TRIG_COLIDANTE_ID FOR COLIDANTE
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_COLIDANTE_ID;
END^

CREATE OR ALTER TRIGGER TRIG_COORDENADAS_ID FOR COORDENADAS
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_COORDENADAS_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TESTIGO_ID FOR TESTIGO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TESTIGO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_ORDEN_DEFUNCION_ID FOR ORDEN_DEFUNCION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ORDEN_DEFUNCION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TESTAMENTO_HEREDITARIO_ID FOR TESTAMENTO_HEREDITARIO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TESTAMENTO_HEREDITARIO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_HEREDEROS_ID FOR HEREDEROS
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_HEREDEROS_ID;
END^

CREATE OR ALTER TRIGGER TRIG_HEREDITARIO_INTESTADO_ID FOR HEREDITARIO_INTESTADO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_HEREDITARIO_INTESTADO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_ANOTACIONES_ID FOR ANOTACIONES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ANOTACIONES_ID;
END^

CREATE OR ALTER TRIGGER TRIG_BANCO_ID FOR BANCO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_BANCO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_PERIODO_ID FOR PERIODO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PERIODO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_CREDITO_ID FOR CREDITO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_CREDITO_ID;
END^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER TRIGGER TRIG_UNIFICACION_ID FOR UNIFICACION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_UNIFICACION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_HIPOTECAS_ID FOR HIPOTECAS
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_HIPOTECAS_ID;
END^

CREATE OR ALTER TRIGGER TRIG_PROPIEDAD_HORIZONTAL_ID FOR PROPIEDAD_HORIZONTAL
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PROPIEDAD_HORIZONTAL_ID;
END^

CREATE OR ALTER TRIGGER TRIG_AMENIDADES_ID FOR AMENIDADES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_AMENIDADES_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DONACIONES_ID FOR DONACIONES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_DONACIONES_ID;
END^

CREATE OR ALTER TRIGGER TRIG_PERMUTAS_ID FOR PERMUTAS
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PERMUTAS_ID;
END^

CREATE OR ALTER TRIGGER TRIG_ADJUDICACION_ID FOR ADJUDICACION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ADJUDICACION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_SOCIOS_ID FOR SOCIOS
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_SOCIOS_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DESMEMBRACION_ID FOR DESMEMBRACION
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_DESMEMBRACION_ID;
END^

CREATE OR ALTER TRIGGER TRIG_DUPLICADO_ID FOR DUPLICADO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_DUPLICADO_ID;
END^

CREATE OR ALTER TRIGGER TRIG_TIPOS_SERVIDUMBRE_ID FOR TIPOS_SERVIDUMBRE
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TIPOS_SERVIDUMBRE_ID;
END^

CREATE OR ALTER TRIGGER TRIG_SERVIDUMBRES_ID FOR SERVIDUMBRES
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_SERVIDUMBRES_ID;
END^

SET TERM ; ^
